# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!

import grpc

from google.cloud.billing_v1.proto import (
    cloud_billing_pb2 as google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2,
)
from google.iam.v1 import iam_policy_pb2 as google_dot_iam_dot_v1_dot_iam__policy__pb2
from google.iam.v1 import policy_pb2 as google_dot_iam_dot_v1_dot_policy__pb2


class CloudBillingStub(object):
    """Retrieves GCP Console billing accounts and associates them with projects.
  """

    def __init__(self, channel):
        """Constructor.

    Args:
      channel: A grpc.Channel.
    """
        self.GetBillingAccount = channel.unary_unary(
            "/google.cloud.billing.v1.CloudBilling/GetBillingAccount",
            request_serializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.GetBillingAccountRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.BillingAccount.FromString,
        )
        self.ListBillingAccounts = channel.unary_unary(
            "/google.cloud.billing.v1.CloudBilling/ListBillingAccounts",
            request_serializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.ListBillingAccountsRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.ListBillingAccountsResponse.FromString,
        )
        self.UpdateBillingAccount = channel.unary_unary(
            "/google.cloud.billing.v1.CloudBilling/UpdateBillingAccount",
            request_serializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.UpdateBillingAccountRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.BillingAccount.FromString,
        )
        self.CreateBillingAccount = channel.unary_unary(
            "/google.cloud.billing.v1.CloudBilling/CreateBillingAccount",
            request_serializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.CreateBillingAccountRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.BillingAccount.FromString,
        )
        self.ListProjectBillingInfo = channel.unary_unary(
            "/google.cloud.billing.v1.CloudBilling/ListProjectBillingInfo",
            request_serializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.ListProjectBillingInfoRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.ListProjectBillingInfoResponse.FromString,
        )
        self.GetProjectBillingInfo = channel.unary_unary(
            "/google.cloud.billing.v1.CloudBilling/GetProjectBillingInfo",
            request_serializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.GetProjectBillingInfoRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.ProjectBillingInfo.FromString,
        )
        self.UpdateProjectBillingInfo = channel.unary_unary(
            "/google.cloud.billing.v1.CloudBilling/UpdateProjectBillingInfo",
            request_serializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.UpdateProjectBillingInfoRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.ProjectBillingInfo.FromString,
        )
        self.GetIamPolicy = channel.unary_unary(
            "/google.cloud.billing.v1.CloudBilling/GetIamPolicy",
            request_serializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.GetIamPolicyRequest.SerializeToString,
            response_deserializer=google_dot_iam_dot_v1_dot_policy__pb2.Policy.FromString,
        )
        self.SetIamPolicy = channel.unary_unary(
            "/google.cloud.billing.v1.CloudBilling/SetIamPolicy",
            request_serializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.SetIamPolicyRequest.SerializeToString,
            response_deserializer=google_dot_iam_dot_v1_dot_policy__pb2.Policy.FromString,
        )
        self.TestIamPermissions = channel.unary_unary(
            "/google.cloud.billing.v1.CloudBilling/TestIamPermissions",
            request_serializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.TestIamPermissionsRequest.SerializeToString,
            response_deserializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.TestIamPermissionsResponse.FromString,
        )


class CloudBillingServicer(object):
    """Retrieves GCP Console billing accounts and associates them with projects.
  """

    def GetBillingAccount(self, request, context):
        """Gets information about a billing account. The current authenticated user
    must be a [viewer of the billing
    account](https://cloud.google.com/billing/docs/how-to/billing-access).
    """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListBillingAccounts(self, request, context):
        """Lists the billing accounts that the current authenticated user has
    permission to
    [view](https://cloud.google.com/billing/docs/how-to/billing-access).
    """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateBillingAccount(self, request, context):
        """Updates a billing account's fields.
    Currently the only field that can be edited is `display_name`.
    The current authenticated user must have the `billing.accounts.update`
    IAM permission, which is typically given to the
    [administrator](https://cloud.google.com/billing/docs/how-to/billing-access)
    of the billing account.
    """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateBillingAccount(self, request, context):
        """Creates a billing account.
    This method can only be used to create
    [billing subaccounts](https://cloud.google.com/billing/docs/concepts)
    by GCP resellers.
    When creating a subaccount, the current authenticated user must have the
    `billing.accounts.update` IAM permission on the master account, which is
    typically given to billing account
    [administrators](https://cloud.google.com/billing/docs/how-to/billing-access).
    This method will return an error if the master account has not been
    provisioned as a reseller account.
    """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListProjectBillingInfo(self, request, context):
        """Lists the projects associated with a billing account. The current
    authenticated user must have the `billing.resourceAssociations.list` IAM
    permission, which is often given to billing account
    [viewers](https://cloud.google.com/billing/docs/how-to/billing-access).
    """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetProjectBillingInfo(self, request, context):
        """Gets the billing information for a project. The current authenticated user
    must have [permission to view the
    project](https://cloud.google.com/docs/permissions-overview#h.bgs0oxofvnoo
    ).
    """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateProjectBillingInfo(self, request, context):
        """Sets or updates the billing account associated with a project. You specify
    the new billing account by setting the `billing_account_name` in the
    `ProjectBillingInfo` resource to the resource name of a billing account.
    Associating a project with an open billing account enables billing on the
    project and allows charges for resource usage. If the project already had a
    billing account, this method changes the billing account used for resource
    usage charges.

    *Note:* Incurred charges that have not yet been reported in the transaction
    history of the GCP Console might be billed to the new billing
    account, even if the charge occurred before the new billing account was
    assigned to the project.

    The current authenticated user must have ownership privileges for both the
    [project](https://cloud.google.com/docs/permissions-overview#h.bgs0oxofvnoo
    ) and the [billing
    account](https://cloud.google.com/billing/docs/how-to/billing-access).

    You can disable billing on the project by setting the
    `billing_account_name` field to empty. This action disassociates the
    current billing account from the project. Any billable activity of your
    in-use services will stop, and your application could stop functioning as
    expected. Any unbilled charges to date will be billed to the previously
    associated account. The current authenticated user must be either an owner
    of the project or an owner of the billing account for the project.

    Note that associating a project with a *closed* billing account will have
    much the same effect as disabling billing on the project: any paid
    resources used by the project will be shut down. Thus, unless you wish to
    disable billing, you should always call this method with the name of an
    *open* billing account.
    """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetIamPolicy(self, request, context):
        """Gets the access control policy for a billing account.
    The caller must have the `billing.accounts.getIamPolicy` permission on the
    account, which is often given to billing account
    [viewers](https://cloud.google.com/billing/docs/how-to/billing-access).
    """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetIamPolicy(self, request, context):
        """Sets the access control policy for a billing account. Replaces any existing
    policy.
    The caller must have the `billing.accounts.setIamPolicy` permission on the
    account, which is often given to billing account
    [administrators](https://cloud.google.com/billing/docs/how-to/billing-access).
    """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def TestIamPermissions(self, request, context):
        """Tests the access control policy for a billing account. This method takes
    the resource and a set of permissions as input and returns the subset of
    the input permissions that the caller is allowed for that resource.
    """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CloudBillingServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetBillingAccount": grpc.unary_unary_rpc_method_handler(
            servicer.GetBillingAccount,
            request_deserializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.GetBillingAccountRequest.FromString,
            response_serializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.BillingAccount.SerializeToString,
        ),
        "ListBillingAccounts": grpc.unary_unary_rpc_method_handler(
            servicer.ListBillingAccounts,
            request_deserializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.ListBillingAccountsRequest.FromString,
            response_serializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.ListBillingAccountsResponse.SerializeToString,
        ),
        "UpdateBillingAccount": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateBillingAccount,
            request_deserializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.UpdateBillingAccountRequest.FromString,
            response_serializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.BillingAccount.SerializeToString,
        ),
        "CreateBillingAccount": grpc.unary_unary_rpc_method_handler(
            servicer.CreateBillingAccount,
            request_deserializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.CreateBillingAccountRequest.FromString,
            response_serializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.BillingAccount.SerializeToString,
        ),
        "ListProjectBillingInfo": grpc.unary_unary_rpc_method_handler(
            servicer.ListProjectBillingInfo,
            request_deserializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.ListProjectBillingInfoRequest.FromString,
            response_serializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.ListProjectBillingInfoResponse.SerializeToString,
        ),
        "GetProjectBillingInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetProjectBillingInfo,
            request_deserializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.GetProjectBillingInfoRequest.FromString,
            response_serializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.ProjectBillingInfo.SerializeToString,
        ),
        "UpdateProjectBillingInfo": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateProjectBillingInfo,
            request_deserializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.UpdateProjectBillingInfoRequest.FromString,
            response_serializer=google_dot_cloud_dot_billing__v1_dot_proto_dot_cloud__billing__pb2.ProjectBillingInfo.SerializeToString,
        ),
        "GetIamPolicy": grpc.unary_unary_rpc_method_handler(
            servicer.GetIamPolicy,
            request_deserializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.GetIamPolicyRequest.FromString,
            response_serializer=google_dot_iam_dot_v1_dot_policy__pb2.Policy.SerializeToString,
        ),
        "SetIamPolicy": grpc.unary_unary_rpc_method_handler(
            servicer.SetIamPolicy,
            request_deserializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.SetIamPolicyRequest.FromString,
            response_serializer=google_dot_iam_dot_v1_dot_policy__pb2.Policy.SerializeToString,
        ),
        "TestIamPermissions": grpc.unary_unary_rpc_method_handler(
            servicer.TestIamPermissions,
            request_deserializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.TestIamPermissionsRequest.FromString,
            response_serializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.TestIamPermissionsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "google.cloud.billing.v1.CloudBilling", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
